version: "3.9"

services:
  autodeploy:
    build:
      context: .
    container_name: ${CONTAINER_NAME}
    ports:
      - "4021:4021" # Porta 3002 no host para 3000 no container
    env_file:
      - .env
    environment:
      - SAP_USER=integracao02
      - SAP_PWD=sapHS02
      - SAP_DB=OURO
      - SAP_URL=https://sap-hstern-sl.skyinone.net:50000/b1s/v1
      - SERVIDOR_PROD=10.1.0.49
      - ORCL_USER=${ORCL_USER} #CONSULTA_SAP
      - ORCL_PWD=${ORCL_PWD}
      - ORCL_CS=${ORCL_CS} #10.1.0.158:1528/hs_prd
      - NODE_ENV=production
      - TZ=America/Sao_Paulo
    volumes:
      - .:/dados # Para permitir edição local durante o desenvolvimento #
    restart: unless-stopped
volumes:
  logs:
